port: 12301
log:
  path: stdout
  sample: 20000
store:
  path: data
  maxLogSize: 1073741824
  maxDays: 7
  clearInterval: 10
  waitDelLockTimeoutMs: 3000
  folderCount: 10
worker:
  buffSize: 1000
  waitMsgTimeout: 1000
  waitMsgTimeoutLogSample: 30
timeout:
  net:
    write: 1000
  server:
    alive: 30000
background:
  life:
     defaultScanSec: 7200
  delay:
     firstExec: 1


