port: 8083
log:
  path: stdout
  sample: 1000
store:
  path: mq-data
  maxLogSize: 2147483648
  maxDays: 7
  clearInterval: 10
  waitDelLockTimeoutMs: 3000
worker:
  buffSize: 1000
  waitTimeoutMs: 500
net:
  writeTimeout: 1
life:
  defaultScanSec: 7200
delay:
  firstExec: 1


