port: 12301
log:
  path: stdout
  sample: 10000
store:
  path: data
  maxLogSize: 1073741824
  flushLevel: 1
  maxDays: 7
  clearInterval: 10
  waitDelLockTimeoutMs: 3000
  noCache: false
  folderCount: 10
worker:
  buffSize: 1000
  waitMsgTimeout: 1000
  waitMsgTimeoutLogSample: 30
timeout:
  net:
    write: 1000
  server:
    alive: 30000
background:
    defaultScanSecond: 7200
    firstExecSecond: 1


